# Generated by Django 4.0.2 on 2022-06-05 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserDetails',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('username', models.CharField(db_column='Username', max_length=256, unique=True)),
                ('fullname', models.TextField(db_column='FullName')),
                ('email', models.CharField(db_column='Email', max_length=256)),
                ('image', models.TextField(db_column='Image')),
                ('status', models.TextField(db_column='Status')),
            ],
            options={
                'db_table': 'user_details',
            },
        ),
    ]
