# Generated by Django 4.0.1 on 2022-05-31 04:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_remove_profile_email_profile_address_profile_phone_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
