# Generated by Django 4.0.1 on 2022-05-31 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_profile_birthday_profile_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='birthday',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
