# Generated by Django 4.0.1 on 2022-05-31 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_profile_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='email',
        ),
    ]
