# Generated by Django 4.0.1 on 2022-06-27 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_profile_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='pic',
            field=models.FileField(blank=True, upload_to='uploads'),
        ),
    ]
