# Generated by Django 4.0.1 on 2022-06-28 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_followerscount_alter_profile_cover_pic_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='user',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
