# Generated by Django 4.0.1 on 2022-06-28 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_post_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='user',
        ),
    ]
