# Generated by Django 4.0.1 on 2022-07-01 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_remove_post_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='followerscount',
            name='user_id',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
