# Generated by Django 4.0.1 on 2022-07-02 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_post_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hawaa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no', models.CharField(default=True, max_length=100)),
                ('body', models.TextField()),
            ],
        ),
    ]
