# Generated by Django 4.0.1 on 2022-07-02 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_hawaa'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FollowersCount',
            new_name='FollowerCount',
        ),
    ]
