# Generated by Django 4.0.1 on 2022-07-02 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_alter_followercount_profile_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='followercount',
            name='profile_name',
        ),
        migrations.AddField(
            model_name='followercount',
            name='user_id',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
