# Generated by Django 4.0.1 on 2022-07-03 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_remove_followercount_profile_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='post',
        ),
        migrations.DeleteModel(
            name='FollowerCount',
        ),
        migrations.DeleteModel(
            name='LikePost',
        ),
        migrations.RemoveField(
            model_name='post',
            name='user_name',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
